### ISSUE TITLE
Recursive insert breaks when association has a validation on a foreign key ID

### ISSUE THREAD

**Issue by ibrahima** [zdennis/activerecord-import#726] opened 2021-03-19 21:26 UTC
Hi! Apologies if this has been brought up before but I could not find anything regarding this issue.

I have recently been upgrading our version of activerecord-import through several versions (we were on v0.16.0 so pretty old...) and I ran into a minor issue where doing a recursive import failed when the nested association had a validation on the foreign key's presence rather than the relation itself. Now, I am not sure whether there's a particular reason we have this validation and we may just get rid of it because the distinction between the foreign key and the relation doesn't seem particularly important. It probably makes more sense to have foreign key constraints at the database level. But I do know that this used to work on v0.16.0, though maybe that version wasn't really running validations in the first place?

Here's a really simple example of the issue, which will break a few of the tests for recursive imports. It works fine if the validation is `validates :book, presence: true` and that in fact is redundant since Rails already requires belongs_to associations since Rails 5, but our app is older than that so we might just have had some older validations lying around that are no longer needed.

https://github.com/zdennis/activerecord-import/compare/master...ibrahima:validates_fk_id

I don't know if it's possible to make this work or if it even should work, but I just wanted to pass this along and document it in case anyone else runs into this issue. In theory it seems like once the first insert finishes we do have the primary key IDs for the first set of records, and so the recursive insert would be able to supply the foreign key IDs for validation, but perhaps the validation is happening before that or something.

Thanks for the great work on this gem!

**Comment by jkowens** [comment] 2021-03-19 21:38
Hi @ibrahima can you describe how it failed and what the error was? Some sample code might also be helpful, thanks!

**Comment by ibrahima** [comment] 2021-03-19 22:34
Hi @jkowens, the issue was that none of the records were imported, and when I check the failed_instances method, I see that the instances failed to be imported because the nested record was invalid. [I've made a PR](https://github.com/zdennis/activerecord-import/pull/727) just to get a CI run for my example so hopefully that will help demonstrate it. For example, in the test suite you would get a test failure like this:


```
2) Failure:
importing objects with associations#test_importing objects with associations_imports first level associations [/.../activerecord-import/test/support/shared_examples/recursive_import.rb:26]:
"Book.count" didn't change by 6.
Expected: 8
  Actual: 2
```

And the error would probably be something like `chapters is invalid`. Now, one could argue that this validation is somewhat pointless and I think that may be true (besides the Rails 5 belongs_to change, we are using more foreign key constraints these days anyway), but if it is an issue I just wanted to document it for others who may run into this.

**Comment by jkowens** [comment] 2021-03-19 23:19
Hm if the association's foreign key field is not being populated on recursive import that does sound like it's probably a bug. Thanks for the report 👍

**Comment by ibrahima** [comment] 2021-03-20 06:56
Well the interesting thing is that if I add validate: false it will fill it in fine and both tables get imported correctly. It's just that the validation is happening before that gets filled in it would seem.

**Comment by 2rba** [comment] 2021-04-10 20:40
not sure that is related, I am having trouble with a foreign key. it worked fine with Rails 5 but with Rails 6 import does not validate if the foreign key record present.
I have installed fresh Rails `6.0.3.6`
activerecord-import (1.0.8)
postgres schema:
```
ActiveRecord::Schema.define(version: 2021_04_10_202255) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "comments", force: :cascade do |t|
    t.bigint "post_id"
    t.string "body"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["post_id"], name: "index_comments_on_post_id"
  end

  create_table "posts", force: :cascade do |t|
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  add_foreign_key "comments", "posts"
end
```

When I do in console `Comment.import [post_id: 1111, body: 'a']` I got the error 
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  insert or update on table "comments" violates foreign key constraint "fk_rails_2fd19c0db7")
DETAIL:  Key (post_id)=(1111) is not present in table "posts".
```

But in Rails 5 `activerecord-import` checked foreign keys and returned response instead of the error.

Any advice highly appreciated.
Thank you

**Comment by jkowens** [comment] 2021-05-15 16:10
@ibrahima would you mind stepping through some code for me? It looks like we try to load association ids before validating here: https://github.com/zdennis/activerecord-import/blob/82ac6f9c90b216be4f1125b36ba7d0d1608dfa6c/lib/activerecord-import/import.rb#L593

Could you see what goes wrong in your codebase?

**Comment by jkowens** [comment] 2021-07-16 14:58
@ibrahima after digging into this issue, I realized it is a problem that we unfortunately might not be able to resolve. The issue is that "recursive import" isn't really recursive. In our example of Book -> Chapter, Book gets imported first then Chapter. The issue with validating book_id on Chapter is that when Book gets imported Chapter will be invalid because book_id isn't set (it doesn't exist yet). Since Book has an invalid association it fails validation.

The only option I can think of would be to disable validating associations all together on import, and I don't think that would be desirable...so I think this is a quirk we'll just have to live with unless someone comes up with a great idea 😅

**Closed** 2021-10-10 20:07 UTC
Labels: bug

**Comment by airblade** [comment] 2023-05-03 09:48
@ibrahima @jkowens Thanks for the work you did on this issue.  I just noticed I've been having the same problem and reading this issue saved me lots of time :)
