### ISSUE TITLE
Duplicates record if initializing object from parent

### ISSUE THREAD

**Issue by mariusz360** [zdennis/activerecord-import#142] opened 2014-04-30 19:01 UTC
I came across an odd issue where the import would duplicate records if I initalized them from the parent.

For simplicity, I'll show a User and Event example
```ruby
class User
  has_many :events
  
  #broken - creates 20 events
  def broken_create_many_events 
    events_to_import = []
    10.times.do
      events_to_import.push(events.new(uuid: SecureRandom.uuid))
    end
    Event.import(events_to_import)
  end

  #works - creates 10 events
  def working_create_many_events
    events_to_import = []
    10.times.do
      events_to_import.push(Event.new(user_id: id, uuid: SecureRandom.uuid))
    end
    Event.import(events_to_import)
  end
end
```

Any ideas?

**Comment by jkowens** [comment] 2016-10-07 18:26
I was unable to reproduce, so I'm closing. Feel free to open if this is still an issue.

**Closed by jkowens** 2016-10-07 18:26 UTC
