### ISSUE TITLE
ActiveRecord association loads incorrect association for an object when importing

### ISSUE THREAD

**Issue by sophylee** [zdennis/activerecord-import#402] opened 2017-04-10 19:06 UTC
### Steps to reproduce
We're cloning a set of `waypoints` objects, each associated with `participations`. `participations` are cloned for the `waypoints` using `dup`. 

I noticed that some `waypoints` were missing their `participations` associations. It turns out than these problematic `waypoints` created using activerecord-import initialize `participations` that have a `waypoint_id` different from the `id` that they're associated with. Putting a debugger in `ActiveRecord#associations`, here's the output: 

```ruby
    150: def association(name) #:nodoc:
    151:   association = association_instance_get(name)
 => 152:   binding.pry if name == :participations && association.present? && self.id.present?
    153:
    154:   if association.nil?
    155:     raise AssociationNotFoundError.new(self, name) unless reflection = self.class._reflect_on_association(name)
    156:     association = reflection.association_class.new(self, reflection)
    157:     association_instance_set(name, association)
    158:   end
    159:
    160:   association
    161: end

association.inspect # returns an object with waypoint_id: 205
self.id # returns 206
```

Because 205 != 206, these `participations` never successfully get saved. I'm filing the bug here instead of with Rails because creating the waypoints one by one without activerecord-import never results in the bug. 

### System configuration
**Rails version**: 4.1.6

**Ruby version**: ruby 2.1.1

**Comment by jkowens** [comment] 2017-04-10 19:37
Hi, can you confirm you have the latest version of  activerecord-import? Also, could you provide a basic code sample of how to reproduce this issue? I have a feeling there might be an issue with the way you are assigning associated participations to the waypoint dup.

**Comment by jkowens** [comment] 2017-04-10 20:28
I guess what I'm asking is are you sure you are setting the `waypoint_id` of the duped waypoint on all of the duped participations?

**Comment by sophylee** [comment] 2017-04-12 00:05
@jkowens I did a fair bit of digging after your comment and found that the `participations` we were creating for the cloned `waypoints` were cloned off an existing `waypoint`'s `participations`, which meant that the cloned `participations` were associated with the original `waypoint`. So, I instantiated the `participations` with `waypoint_id` = `id` of the new cloned waypoint. The problem is that the new cloned waypoint doesn't yet have a waypoint, so that didn't work. So I tried setting `participations.waypoint = new_waypoint`, and that also doesn't work.

**Comment by sophylee** [comment] 2017-04-12 00:08
Oh and, `waypoint` belongs to a parent object. We're seeing this issue with another association where there are multiple associations from parent object A which is associated with B (in this case, waypoints) which is associated with C (participations).

**Comment by jkowens** [comment] 2017-04-12 02:39
@sophylee my head is spinning a bit trying to follow everything you mentioned 😜 

So for the original issue, have you tried something like this?

```
new_waypoint = old_waypoint.dup
old_waypoint.participations.each do |participation|
  new_participation = participation.dup
  new_participation.waypoint_id = nil
  new_waypoint.participations << new_participation
end
```

I *think* this will setup duped participations so they they are assigned the new waypoint's id.

**Comment by jkowens** [comment] 2017-04-17 13:37
Closing for now. If there is still an issue feel free to add more details and we can reopen.

**Closed by jkowens** 2017-04-17 13:37 UTC
Labels: waiting-on-OP-response

**Comment by sophylee** [comment] 2017-04-17 17:38
@jkowens sorry for the delayed response. I actually did try your suggestion last week and it unfortunately did not work either. Our workaround works for now and I'll reopen if it becomes a performance issue to the point of needing reinvestigation. Thanks!

**Comment by sophylee** [comment] 2017-09-07 01:26
@jkowens this original issue is causing some serious performance issues, so I'd like to request that the issue gets reopened as we really need your help. We dug deep into the gem import.rb file itself and here is what we found: 

### Our schema

`alpha` has_one `beta`
`beta` has_many `kappa`
`kappa` belongs_to `start_delta` AND `kappa` belongs_to `end_delta` (think of delta as two endpoints of a vertex - there's a start and an end) 
`delta` has_many `epsilon`
`phi` is a join table of `alpha` and `mu` (the only columns in `phi` are `alpha_id` and `mu_id`)

### Issue 1: The insert statement for `kappa` has null values for `start_delta` and `end_delta`

Here is how we set the `kappa` and `delta` relationship:

1. Clone one of the `delta` using `delta.dup`. 
2. Clone the `kappa` using `kappa.dup`.
3. `kappa.assign_attributes: (start_delta: duped_delta_1, end_delta: duped_delta_2)` 

Here's the insert statement that results from the gem, pulled from our test logs -- line 3 is the one you want to pay attention to: 

```sql
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "alpha" ("id", ...) VALUES (nextval('public.alpha_id_seq'), ...) RETURNING "id"
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "beta" ("id","alpha_id", ...) VALUES (nextval('public.beta_id_seq'),266, ...) RETURNING "id"
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "kappa" ("id","beta_id","start_delta_id","end_delta_id",...) VALUES (nextval('public.kappa_id_seq'),226,NULL,NULL,...) RETURNING "id"
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "delta" ("id","alpha_id",...) VALUES (nextval('public.delta_id_seq'),266,...) RETURNING "id"
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "epsilon" ("id","delta_id",...) VALUES (nextval('public.epsilon_id_seq'),451,...) RETURNING "id"
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "phi" ("id","alpha_id","mu_id",...) VALUES (nextval('public.phi_id_seq'),266,NULL,...) RETURNING "id"
```

Note how two nulls are getting inserted. 

The workaround is for us to do the following immediately after the import: 

```ruby
alpha.beta.kappas.each do |kappa|
  kappa.start_delta_id = kappa.start_delta.id
  kappa.end_delta_id = kappa.end_delta.id
  kappa.save
end
```

Those individual saves result in the type of N+1 inserts we were hoping to avoid with this import gem. 

Something we tried was to switch the [two lines here](https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L726-L727) in a fork of your gem so that we load `has_many` relationships before `has_one` relationships. That did result in the `has_many` relationships getting inserted first, but didn't change the sql statement in any of the inserts. Our reasoning was that maybe the `delta`s needed to be inserted first before `kappas` could reference the `id` of a `delta` but that doesn't seem to be true.

### Issue 2: `mu` never gets inserted

Here's how we set the relationship pre-import: 

```ruby
alpha.phis.build(mu: Mu.new(custom_attribute: foo))
```

Here's the insert statement that results from the gem, pulled from our test logs -- line 6 is the one you want to pay attention to: 

```sql
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "alpha" ("id", ...) VALUES (nextval('public.alpha_id_seq'), ...) RETURNING "id"
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "beta" ("id","alpha_id", ...) VALUES (nextval('public.beta_id_seq'),266, ...) RETURNING "id"
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "kappa" ("id","beta_id","start_delta_id","end_delta_id",...) VALUES (nextval('public.kappa_id_seq'),226,NULL,NULL,...) RETURNING "id"
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "delta" ("id","alpha_id",...) VALUES (nextval('public.delta_id_seq'),266,...) RETURNING "id"
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "epsilon" ("id","delta_id",...) VALUES (nextval('public.epsilon_id_seq'),451,...) RETURNING "id"
Class Create Many Without Validations Or Callbacks (0.0ms)  INSERT INTO "phi" ("id","alpha_id","mu_id",...) VALUES (nextval('public.phi_id_seq'),266,NULL,...) RETURNING "id"
```

Note how the gem is inserting a null for mu_id, AND there is no insert statement for Mu at all.

The workaround is for us to do the following immediately after the import: 

```ruby
alpha.phis.each(&:save)
```

which again is super slow when we're inserting ~100 `alpha`s and their associations at a time.

### Issue 3 (minor): Bug in logging

There seems to be a bug in [this line](https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L641). 

`self.class.name` will always return `Class` so as you can see in the sql logs I pasted above, none of the gem-generated insert statements actually describe what class' table is being updated. It just says "Class Create" instead of "Class Alpha Create" or similar.

Lmk if there's anything else I can provide.

**Comment by jkowens** [comment] 2017-09-07 03:12
@sophylee first of all, thanks tracking down the bug int the logging. I pushed up a fix to master that will be part of the next release 👍 

I think the issues you are describing come down to the order you are trying to import some of these models. The import only runs down has_one/has_many associations, so once you get to a belongs_to you are in trouble.

In this scenario I think as you build out your data hierarchy you'll need to keep an array of delta objects and an array of mu objects. So then you could do something like:

```
# import deltas and epsilons
Delta.import deltas 

Mu.import mus

# import alphas, betas, kappas, phis
# kappas should reference deltas that already have ids from database
# phis should reference mus that already of ids from database
Alpha.import alphas
```

Hopefully something like that is doable. Keep us posted.

**Comment by sophylee** [comment] 2017-09-07 03:39
⚡️ woah, that was fast. We'll give it a try tomorrow. Thanks so much.

**Comment by sophylee** [comment] 2017-09-08 01:53
Couldn't get it working but we'll keep trying.

**Comment by jkowens** [comment] 2017-09-08 02:28
If you could create a sample Github repo that demonstrates this issue, that might help us think through a solution.

**Comment by sophylee** [comment] 2017-09-11 23:12
@jkowens we pointed the gem to master and tried what you suggested -- it almost worked, with some tweaks. Here's the final, working solution: 

```ruby
# had to add this
Epsilon.import epsilons, recursive: false, validate: false 

# recursive had to be false
Delta.import deltas, recursive: false, validate: false

# this was fine as-is
Mu.import mus, validate: false

# this was fine as-is
Alpha.import alphas, recursive: true, validate: false
```

Thanks!

**Comment by sophylee** [comment] 2017-09-12 01:26
@jkowens actually..that didn't quite work and we think that it's because of a circular dependency. There is one relationship we forgot to provide which is that Delta belongs_to Alpha. 

This is what we ultimately had to do:

```ruby
Delta.import deltas, recursive: true, validate: false
Mu.import mus, validate: false
Alpha.import alphas, recursive: true, validate: false

# This is the only new thing we needed to add. The INSERT for Delta was inserting deltas with a NULL alpha_id
alphas.each { |t| t.deltas.each { |d| d.update_column(:alpha_id, alpha.id) } }
```

Do you have any ideas for this last line?

**Comment by jkowens** [comment] 2017-09-12 05:07
Yikes, that is a bit of a monkey wrench. Well, that definitely means you'll need to break up the import into a few more pieces. The following should do the trick:

```
alphas = []
betas  = []
deltas = []
phis   = []
mus    = []

20.times do
  alpha = Alpha.new
  betum = Betum.new(alpha: alpha)

  betas << betum

  2.times do |i|
    start_deltum = Deltum.new(alpha: alpha)
    end_deltum = Deltum.new(alpha: alpha)

    2.times do
      start_deltum.epsilons << Epsilon.new
      end_deltum.epsilons << Epsilon.new
    end

    deltas << start_deltum
    deltas << end_deltum

    kappa = Kappa.new(start_deltum: start_deltum, end_deltum: end_deltum)
    betum.kappas << kappa

    mu = Mu.new(value: "Test #{i}")
    mus << mu

    phi = Phi.new(alpha: alpha, mu: mu)
    phis << phi

    alpha.phis << phi
  end

  alpha.betum = betum
  alphas << alpha
end

# import alphas
Alpha.import alphas, validate: false

# import deltas and epsilons
# deltas should reference alphas that already have ids from database
Deltum.import deltas, recursive: true, validate: false

# import betas and kappas
# kappas should reference deltas that already have ids from database
Betum.import betas, recursive: true, validate: false

# import mus
Mu.import mus, validate: false

# import phis
# phis should reference mus that already of ids from database
Phi.import phis, validate: false
```

**Comment by jkowens** [comment] 2017-09-13 00:49
The latest update for syncing belongs_to association ids with a foreign key column has been released in v0.20.0 🙌

**Comment by sophylee** [comment] 2017-09-13 19:19
@jkowens did you happen to merge everything in master into the new release? We grabbed the most recent version and it broke a bunch of our tests. 

cc @srgoldman so you can respond directly to Jordan.

**Comment by sophylee** [comment] 2017-09-13 21:46
@jkowens never mind! Must've been a timing issue. Version 0.20.0 works. 

Final outcome is that we reduced total transaction time from ~108 seconds to about 10 seconds. We'll live with that and consider it a success for now :) The portion that activerecord-import takes was reduced from ~40 seconds to ~3 seconds through your help and gem update. Thanks a TON, this makes a huge difference for our business.

**Comment by sophylee** [comment] 2017-09-13 21:48
Seth says we owe you a 🍺

**Comment by jkowens** [comment] 2017-09-14 03:14
Haha well if I make it out to the west coast I might cash in on that 👍   Thanks for the update, I enjoy hearing about activerecord-import wins!
