### ISSUE TITLE
unable to create db

### ISSUE THREAD

**Issue by rockrep** [zdennis/activerecord-import#8] opened 2010-12-13 21:32 UTC
If my database is already created/migrated, and I add this gem to my Gemfile, everything is fine.   If however, I rake db:drop; rake db:create with this gem in my Gemfile I get the error "Unknown database 'myproject_dev'.   Removing this gem from Gemfile and re-running bundle install, fixes the issue.   

It seems like a class loading issue caused by this gem.  I get a similar error if I set config.cache_classes = true in development.rb.   Hopefully this issue can be resolved, because I like the solution.  Thanks.

Attaching stack trace:
rake db:create --trace
rake aborted!
Unknown database 'myproject_dev'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/mysql_adapter.rb:600:in `real_connect'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/mysql_adapter.rb:600:in `connect_without_redhillonrails_core'
.../gems/redhillonrails_core-1.0.8/lib/red_hill_consulting/core/active_record/connection_adapters/mysql_adapter.rb:11:in `connect'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/mysql_adapter.rb:164:in `initialize'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/mysql_adapter.rb:36:in `new'
../gems/activerecord-3.0.3/lib/active_record/connection_adapters/mysql_adapter.rb:36:in `mysql_connection'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:228:in `send'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:228:in `new_connection'
../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:236:in `checkout_new_connection'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `checkout'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:186:in `loop'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:186:in `checkout'
~/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/monitor.rb:242:in `synchronize'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:185:in `checkout'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:93:in `connection'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:316:in `retrieve_connection'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:97:in `retrieve_connection'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:89:in `connection'
.../gems/activerecord-import-0.2.3/lib/activerecord-import.rb:5:in `establish_connection'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:80:in `establish_connection_without_activerecord_import'
.../gems/activerecord-import-0.2.3/lib/activerecord-import.rb:4:in `establish_connection'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:60:in `establish_connection_without_activerecord_import'
.../gems/activerecord-import-0.2.3/lib/activerecord-import.rb:4:in `establish_connection'
.../gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:55:in `establish_connection_without_activerecord_import'
.../gems/activerecord-import-0.2.3/lib/activerecord-import.rb:4:in `establish_connection'
.../gems/activerecord-3.0.3/lib/active_record/railtie.rb:59
~/.rvm/gems/ruby-1.8.7-p174@trakstar/gems/activesupport-3.0.3/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
.../gems/activesupport-3.0.3/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
.../gems/activesupport-3.0.3/lib/active_support/lazy_load_hooks.rb:26:in `on_load'
.../gems/activerecord-3.0.3/lib/active_record/railtie.rb:57
.../gems/railties-3.0.3/lib/rails/initializable.rb:25:in `instance_exec'
.../gems/railties-3.0.3/lib/rails/initializable.rb:25:in `run'
.../gems/railties-3.0.3/lib/rails/initializable.rb:50:in `run_initializers'
.../gems/railties-3.0.3/lib/rails/initializable.rb:49:in `each'
.../gems/railties-3.0.3/lib/rails/initializable.rb:49:in `run_initializers'
.../gems/railties-3.0.3/lib/rails/application.rb:134:in `initialize!'
.../gems/railties-3.0.3/lib/rails/application.rb:77:in `send'
.../gems/railties-3.0.3/lib/rails/application.rb:77:in `method_missing'
./config/environment.rb:5
...

**Comment by jkowens** [comment] 2016-10-08 15:37
I am not able to reproduce this error with the latest version of activerecord-import (0.15.0). I'm closing for now.

**Closed by jkowens** 2016-10-08 15:37 UTC
