### ISSUE TITLE
Is there a reliable new record count when importing and using "on duplicate key update"?

### ISSUE THREAD

**Issue by patakijv** [zdennis/activerecord-import#200] opened 2015-08-30 20:32 UTC
I've been using this import records gem for a while now for fast mysql importing and letting mysql optimize what records need to be added vs updated by leveraging the "on duplicate key update" feature. It works so much faster than trying to determine what records are new at the application layer first. One thing I am missing now that the database is determining if a record needs to be updated vs created as new is the metric of how many records were created from the single import statement. 

Does the gem provide a way to reliably return even just a count of how many new records were created if an array of 10,000 records were sent in and "on duplicate key update" was used and some will be updates vs some new records?

Does using this gem's import method alter or bypass the setting of the ActiveRecord connection.affected_rows value after it is used differently than if the gem isn't used? 

Are there any additional parameters this gem adds that can be useful to determine an accurate count of "added" vs "updated" when a known number of records was imported and using mysql's "on duplicate key update"

**Comment by zdennis** [comment] 2016-04-01 17:22
@patakijv, it currently doesn't not provide this information. It is something we'll look into for a future update.

**Comment by jkowens** [comment] 2016-10-09 03:10
See: http://stackoverflow.com/questions/27552542/affected-rows-for-activerecordbase-connection-execute

> Here is an easy way to get the number of affected rows using the mysql2 adapter. Put this in a file that gets loaded by your app:
> 
> class ActiveRecord::ConnectionAdapters::Mysql2Adapter
>   def affected_rows
>     @connection.affected_rows
>   end
> end
> Then you will be able to run ActiveRecord::Base.connection.affected_rows to get the number of affected rows.
> 

With that you could then do something like this:

```
 Post.import posts, validate: false
 affected_rows = ActiveRecord::Base.connection.affected_rows
 import_size = posts.size
 updated_count = affected_rows - import_size
 new_count = import_size - updated_count
```

Obviously this MySQL only and doesn't take into account concurrency, so I don't see this being added to activerecord-import.

**Comment by jkowens** [comment] 2016-11-07 22:47
Closing for now, this information may have to be calculated by extra sql queries to count records within a transaction or the code above may work for MySQL.

**Closed by jkowens** 2016-11-07 22:47 UTC
Labels: needs-investigation

**Comment by rjosal** [comment] 2016-12-09 01:06
I posted #346, it's a duplicate of this.  But I don't think it should be closed as won't fix.  I'm using the workaround mentioned (although it needs a rescue nil to be safe) but it's not guaranteed to to return what you think, in case some other query happened in between.  Besides, when implementing something like this, best not to drop information on the floor in case somebody wants to use it.

**Comment by jkowens** [comment] 2016-12-09 01:46
That's the thing, I don't think the information is being dropped on the floor...from what I've seen it's really only available as described above. I think I read that since `affected_rows` is per connection you will get counts specific to that connections last transaction. Have you seen otherwise? If you can do some research and report back that would be helpful.
