### ISSUE TITLE
has_many associations don't save with recursive: :true

### ISSUE THREAD

**Issue by rhannequin** [zdennis/activerecord-import#247] opened 2016-03-02 09:01 UTC
Hello,

First, thank you very much for this gem, it is **much** appreciated every day from casual to complex data imports.

I am having troubles with the multi-level feature, when trying to import models with associations. I tried to follow the [multi-level example](https://github.com/zdennis/activerecord-import/wiki#multi-level-example) this way:

I created a blank app with two models:

```
$ bundle exec rails g model Book title:string
$ bundle exec rails g model Review name:string book:references
```

Then I added the association to the `Book` model:

```ruby
class Book < ActiveRecord::Base
  has_many :reviews
end
```

I created a basic rake task with the same code as the example, to insert books with one review in each, and checking at the end if everything went good:

```ruby
task test: :environment do
  Book.delete_all
  Review.delete_all

  books = []
  10.times do |i|
    book = Book.new(title: "Book ##{i}")
    book.reviews.build(name: "Review ##{i}")
    books << book
  end
  Book.import books, recursive: true

  puts "'Book' records count: #{Book.count}"
  puts "Last 'Book' reviews count: #{Book.last.reviews.count}"
  puts "'Review' records count: #{Review.count}"
end
```

What I have in return shows that the books were inserted but not the associated reviews:

```
'Book' records count: 10
Last 'Book' reviews count: 0
'Review' records count: 0
```

I don't know if my way of inserting associated models in database is wrong or if the multi-level feature has an issue, I thought it was the best place to warn about this behaviour has @sferik 's PR #230 (thank you for that btw) was supposed to fix it.

This test was run on Ubuntu 15.10 with:
* `rails` v4.2.5.1
* `activerecord` v4.2.5.1
* `sqlite3` v1.3.11
* `activerecord-import` from Github (at master@df866a4)

This post is a duplicate from my comment on #243.

Thank you.

**Comment by JHFirestarter** [comment] 2016-03-02 13:23
See @allenwlee findings in issue #231 (short answer is to add `autosave: true` and `inverse_of` in your models). 

2 problems I've found with this, in a common use case: 

1. if there's also a model that has a `has_many .. through` association...such as `book` `has_many :reviews` and `has_many :critics, through: :reviews`, `critic` `has_many :reviews` and `has_many :books, through: :reviews`, and finally `review` `belongs_to :book` and `belongs_to :critic`. In this case, what @allenwlee shows will import either books and reviews or critics and reviews (with associations)...but not all 3. The rails docs say `inverse_of` "[does] not work with :through associations"...so I wonder if that's the core problem with the strategy.

2. if the data may have duplicates on multi-index columns...the `on_duplicate_key_ignore: true` option will fail to import a valid unique review if a book is a duplicate of an existing book in the books table (at least in postgresql).

**Comment by JHFirestarter** [comment] 2016-03-02 13:35
also, make sure to [use the latest version](https://rubygems.org/gems/activerecord-import) (0.11.0 was throwing off `select` errors)

**Comment by rhannequin** [comment] 2016-03-02 14:37
@JHFirestarter Thank you for your answer.

Unfortunately I'm facing the same results.

Using the same example project [from the wiki](https://github.com/zdennis/activerecord-import/wiki#multi-level-example), I updated the gem version from Github (now `0.12.0` from df866a4f2a90d52c379fd4764efe2775a89e91ad) and changed my `Book` model to:

```ruby
class Book < ActiveRecord::Base
  has_many :reviews, inverse_of: :book, autosave: true
end
```

The task return is still the same, even if I added `inverse_of` and `autosave`:

```
'Book' records count: 10
Last 'Book' reviews count: 0
'Review' records count: 0
```

**Comment by JHFirestarter** [comment] 2016-03-02 15:26
@rhannequin do you also have `inverse_of` and `autosave: true` in your _Reviews_ model?

**Comment by rhannequin** [comment] 2016-03-02 16:24
@JHFirestarter I did not but just did and unfortunately it's still the same. My rake task hasn't changed and my only two models look like this:

```ruby
class Book < ActiveRecord::Base
  has_many :reviews, inverse_of: :book, autosave: true
end

class Review < ActiveRecord::Base
  belongs_to: :book, inverse_of: :reviews, autosave: true
end
```

Thank you again for your help.

**Comment by JHFirestarter** [comment] 2016-03-02 16:31
Just making sure `belongs_to:` syntax above is bc you're copying from models with different actual names.

**Comment by rhannequin** [comment] 2016-03-02 16:39
Yes sorry, just updated my previous comment, the syntax is supposed to be correct.

**Comment by JHFirestarter** [comment] 2016-03-02 16:40
@rhannequin np. only difference I can tell between what you and I have is (a) the db (I'm sure postgresql) and (b) potentially how we generated associations (i.e. I generated a review migration containing the line `t.belongs_to :book, index: true`) which adds to schema.rb both:
`t.integer "book_id"` and
`add_index "reviews", ["book_id"], name: "index_reviews_on_book_id", using: :btree`

Models contain:
Review model with `belongs_to :book, inverse_of: :reviews, foreign_key: "book_id", autosave: true`
Book model with `has_many :reviews, inverse_of: :book, autosave: true`

I'm out of (limited) ideas after that!

**Comment by rhannequin** [comment] 2016-03-02 16:50
@JHFirestarter My project will be on PostgreSQL but I'm using Sqlite3 for this example as I wanted to only test this multi-level feature of the gem.

My schema has been generated from the migrations mentionned above in my first comment, and looks like this:

```ruby
ActiveRecord::Schema.define(version: 20160302142135) do

  create_table "books", force: :cascade do |t|
    t.string   "title"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "reviews", force: :cascade do |t|
    t.string   "name"
    t.integer  "book_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "reviews", ["book_id"], name: "index_reviews_on_book_id"

end
```

I should mention that I tested the association in the console, it works when I create a `book` with some `reviews`, the records are properly saved.

Thank you again.

**Comment by jkowens** [comment] 2016-03-04 04:38
@rhannequin the :recursive option currently only works for Postgres. The documentation should be updated to make that clear. As of version `0.12.0` `inverse_of` and `autosave` are no longer required.

**Comment by rhannequin** [comment] 2016-03-04 14:49
@jkowens Thank you, that makes sense now. Is there any work in progress to cover Sqlite3 as it may be used on *test* and *development* environments? Or maybe is there a feature inside this gem that makes it impossible to work for Sqlite?

**Comment by jkowens** [comment] 2016-03-04 17:37
I believe this feature could possibly be implemented for sqlite3, but I don't know if there is currently any work in progress to make that happen.

**Comment by yuri-karpovich** [comment] 2016-03-18 08:34
@jkowens and what about mysql2 adapter?

**Comment by jkowens** [comment] 2016-03-18 21:57
@yuri-karpovich you are correct this does not work for mysql2 either.

**Comment by zdennis** [comment] 2016-04-01 17:19
If am reading this thread right the desired outcome is that the `recursive` options works for sqlite and mysql? Is that correct @yuri-karpovich and @jkowens?

**Comment by jkowens** [comment] 2016-04-01 17:40
@zdennis that is how I understand it. In #104 @robmathews provided suggestions on how to possibly implement this functionality for SQLite and MySQL.

**Comment by jkowens** [comment] 2016-06-23 20:06
@rhannequin with the 0.14.0 release sqlite3 now supports recursive import.

**Comment by rhannequin** [comment] 2016-07-22 11:06
@jkowens Thank you, I should be able to test it soon.

**Closed** 2016-10-25 17:45 UTC
Labels: feature-request, mysql

**Comment by yuri-karpovich** [comment] 2016-10-26 11:49
@jkowens and what about mysql?

**Comment by jkowens** [comment] 2016-10-26 22:07
@yuri-karpovich sorry I should have added a comment to this before closing. Unfortunately there currently does not seem to be a good way to implement this feature for MySQL. See PR #279 for some more details. Unless MySQL implements an option to return inserted/updated IDs like PostgreSQL, we will not be able to make this work in a reliable way.

**Comment by yuri-karpovich** [comment] 2016-10-27 09:16
@jkowens thank you for information.

**Comment by hyphenbash** [comment] 2017-07-29 08:56
has this issue regressed on 0.19.1? I am still unable to use recursive import on PostgreSQL. Looking at the logs, I can see that AR objects are recursively created for the associated models, but they're not saved to the database!
