### ISSUE TITLE
timestamp fields are not being properly quoted and insert fails

### ISSUE THREAD

**Issue by gduprey** [zdennis/activerecord-import#639] opened 2019-08-29 20:41 UTC
Using ActiveRecord 4.2.10, ar-import 1.0.2 and Postgresql 11, trying to bulk insert a bunch of records that have the created_at and updated_at timestamp fields.  When I do, the generated SQL for the timestamps is incorrect and the insert blows up.  

Here's the SQL being generated:
`INSERT INTO "admin_log_lines" ("id","log_file_id","private_line","line_status","line_message","record_num","sub_record","record_id","record_key","support_data","created_at","created_by_user_id","updated_at","updated_by_user_id","extended_data") VALUES (53678,1487,'f','notice','Updated Existing GL Transction GL payrol/000048',NULL,'f',NULL,NULL,NULL,(2019-08-29 20:19:00),1,(2019-08-29 20:19:00),1,'{}') RETURNING "id"`

The problem is the created_at and updated_at values are surrounded by parens when they need to be surrounded by single quotes.  In short, the (2019-08-29 20:19:00) values should be '2019-08-29 20:19:00'

With the created/updated_at values as they are now, Postgresql blows up and throws 

`Error execute Payroll Period action - PG::SyntaxError: ERROR:  syntax error at or near "20"
LINE 1: ...ayrol/000048',NULL,'f',NULL,NULL,NULL,(2019-08-29 20:19:00),...
                                                             ^
: INSERT INTO "admin_log_lines" ("id","log_file_id","private_line","line_status","line_message","record_num","sub_record","record_id","record_key","support_data","created_at","created_by_user_id","updated_at","updated_by_user_id","extended_data") VALUES (53678,1487,'f','notice','Updated Existing GL Transction GL payrol/000048',NULL,'f',NULL,NULL,NULL,(2019-08-29 20:19:00),1,(2019-08-29 20:19:00),1,'{}') RETURNING "id"
`

Where the "at or near 20" indicator is the time component of 20:19:00.

The created_at/updated_at Postgresql column data type is 'timestamp with time zone'

Is there a way to get the import SQL code to generate single quotes (which would generally be a pretty good default for any field where there isn't a simple SQL format)?

**Comment by jkowens** [comment] 2019-08-30 03:35
That's strange that it's surrounding timestamps with parens. The only thing I can think of is this line here:

https://github.com/zdennis/activerecord-import/blob/17c3ac05e320fa53247eade7d4ddefb6d1206096/lib/activerecord-import/import.rb#L953

It allows arel subqueries to be used. Is there a chance your timestamp objects respond to `:to_sql`?

**Comment by gduprey** [comment] 2019-08-30 13:52
It does - if I pull up a record in the rails console and then access the create_at.to_sql, I get the time formatted as you see in above report.

My timestamp columns are bog-normal/standard ActiveRecord timestamps - other than I think we use 'timestamp with time zone' vs just 'timestamp' as the postgresql column type.  We haven't overridden/supplemented/altered those fields at all in the models.

**Comment by jkowens** [comment] 2019-08-30 15:34
Can you create a demo rails app that reproduces the issue. I'm not seeing the same behavior.

**Comment by gduprey** [comment] 2019-08-30 16:23
Well, sort of have this figured out.  We had implemented a to_sql method for a number of date, time and related types to handle properly returning the format we need when assembling an SQL query "by hand" (vs arel).  These returned unquoted string forms of the fields.  

Took some digging into our rails initializer code to find this.  I was clued in by your statement implying that normal a timestamp type does not respond to to_sql, but my rails console testing did.

When I use to_sql on a query, it is also unquoted.  So I feel like to_sql returning unquoted strings is matching the existing behavior.  So either:
1) to_sql should return quoted values 
OR
2) ar-import use of to_sql should quote the returned values appropriate to the data type

I'm pretty sure I would guess what you're thinking is, but to quote or not to quote is often a messy and "interpretive" area ;-)

For now, I'm working on resolving use of to_sql and not sure yet if I'll change it to return quotes on the values or use a different method name.  But I have proven that either disabling to_sql or quoting the return value does allow ar-import to work.

So, short of a discussion on quote-or-not, I think we can close this issue.

**Comment by jkowens** [comment] 2019-08-30 20:48
Thanks @gduprey, glad to hear you have a handle on this issue. I think I will go ahead and close this issue since it sounds like you have some feasible options.

**Closed by jkowens** 2019-08-30 20:48 UTC

**Comment by theblang** [comment] 2024-10-14 19:01
Thanks @gduprey ! I hit the same issue (forgot we're overriding `to_sql`), and this issue quickly clued me in!
